---

#Copiar web
- name: Copia de Nginx
  template: 
    src: index.html.j2
    dest: /var/www/html/index.html
  become: yes

- name: Reiniciar servicio
  systemd:
    name: nginx
    state: restarted
  become: yes
