--- 
- name: Install nginx
  apt: name=nginx state=latest
  become: yes

- name: Copiar fichero de configuracion
  template: 
    src: index.nginx-debian.html.j2
    dest: /var/www/html/index.nginx-debian.html
    owner: "{{ ssh_user }}"
    group: "{{ ssh_user }}"

- name: A침adir linea adicional
  lineinfile: dest=/var/www/html/index.nginx-debian.html line="<h2>Con el line in file</h2>" insertafter="Esta p치gina"
  become: yes

- name: a침adir un bloque con blockinfile
  blockinfile:
    dest: /var/www/html/index.nginx-debian.html
    marker: <!--- {mark} ANSIBLE MANAGED BLOCK NGINX --->
    insertafter: "Esta p치gina"
    block: |
      <h2>Con el block in file</h2>
  become: yes
