---
- name: Instalar nginx
  apt: name=nginx state=latest update_cache=yes
  become: yes
- name: Start/Enable
  service:
    name: nginx
    state: started
    enabled: yes
  become: yes
#- name: Instalacion de curl
 # apt: name=curl state=latest
   #become: yes


